# Generated by Django 6.0.1 on 2026-01-27 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auditlog_task_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When task was completed', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours to complete', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_timer_running',
            field=models.BooleanField(default=False, help_text='Whether timer is currently running'),
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Position in kanban column for ordering'),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When work started on this task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_spent_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total minutes spent on task'),
        ),
        migrations.AddField(
            model_name='task',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, help_text='When the current timer session started', null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status', 'position'], name='projects_ta_project_b4d00b_idx'),
        ),
    ]
