# Generated by Django 6.0.1 on 2026-01-27 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_time_tracking_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code for the tab', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon name from lucide-react', max_length=50, null=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order of the section in tabs')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is a default section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sections', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='projects.project')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.tasksection'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'section', 'position'], name='projects_ta_project_6e74d7_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksection',
            index=models.Index(fields=['project', 'position'], name='projects_ta_project_e656ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasksection',
            unique_together={('project', 'slug')},
        ),
    ]
