# Generated by Django 5.1.14 on 2026-01-28 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_alter_invitation_unique_together'),
        ('projects', '0004_tasksection_task_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to_username',
            field=models.CharField(blank=True, help_text='Preserved username if user deleted', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='rich_description',
            field=models.TextField(blank=True, help_text='Rich text description with formatting', null=True),
        ),
        migrations.AddField(
            model_name='tasksection',
            name='banner_url',
            field=models.URLField(blank=True, help_text='Optional banner image URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tasksection',
            name='description',
            field=models.CharField(blank=True, help_text='Section description', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code', max_length=7)),
                ('bg_color', models.CharField(default='#eef2ff', help_text='Background color for light mode', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon name from lucide-react', max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('banner_url', models.URLField(blank=True, help_text='Optional banner image URL', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default labels available to all')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_labels', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_labels', to='orgs.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='projects.tasklabel'),
        ),
        migrations.CreateModel(
            name='FocusedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focused_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes for this focus session', null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focused_by', to='projects.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focused_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-focused_at'],
                'indexes': [models.Index(fields=['user', '-focused_at'], name='projects_fo_user_id_9da2ff_idx')],
                'unique_together': {('user', 'task')},
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(help_text='URL to the file', max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('pdf', 'PDF'), ('other', 'Other')], default='other', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail for images/videos', max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.task')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['task', '-uploaded_at'], name='projects_ta_task_id_3a1937_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_username', models.CharField(blank=True, max_length=30, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_deleted', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('mentions', models.JSONField(blank=True, default=list, help_text='List of mentioned usernames')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.task')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='projects_ta_task_id_21f88e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tasklabel',
            index=models.Index(fields=['organization'], name='projects_ta_organiz_4f3e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklabel',
            index=models.Index(fields=['project'], name='projects_ta_project_fcfa53_idx'),
        ),
    ]
