# Generated by Django 6.0.1 on 2026-01-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_alter_membership_role_invitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
    ]
