# Generated by Django 5.1.14 on 2026-01-28 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_alter_invitation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_create_project', models.BooleanField(default=True)),
                ('admin_delete_project', models.BooleanField(default=True)),
                ('admin_create_task', models.BooleanField(default=True)),
                ('admin_delete_task', models.BooleanField(default=True)),
                ('admin_assign_task', models.BooleanField(default=True)),
                ('admin_view_all_tasks', models.BooleanField(default=True)),
                ('admin_view_unassigned_tasks', models.BooleanField(default=True)),
                ('admin_create_label', models.BooleanField(default=True)),
                ('admin_delete_label', models.BooleanField(default=True)),
                ('admin_manage_timer', models.BooleanField(default=True)),
                ('admin_invite_members', models.BooleanField(default=True)),
                ('admin_remove_members', models.BooleanField(default=False)),
                ('admin_change_member_roles', models.BooleanField(default=False)),
                ('mod_create_project', models.BooleanField(default=True)),
                ('mod_delete_project', models.BooleanField(default=False)),
                ('mod_create_task', models.BooleanField(default=True)),
                ('mod_delete_task', models.BooleanField(default=True)),
                ('mod_assign_task', models.BooleanField(default=True)),
                ('mod_view_all_tasks', models.BooleanField(default=True)),
                ('mod_view_unassigned_tasks', models.BooleanField(default=True)),
                ('mod_create_label', models.BooleanField(default=True)),
                ('mod_delete_label', models.BooleanField(default=False)),
                ('mod_manage_timer', models.BooleanField(default=True)),
                ('mod_invite_members', models.BooleanField(default=False)),
                ('mod_remove_members', models.BooleanField(default=False)),
                ('mod_change_member_roles', models.BooleanField(default=False)),
                ('member_create_project', models.BooleanField(default=False)),
                ('member_delete_project', models.BooleanField(default=False)),
                ('member_create_task', models.BooleanField(default=True)),
                ('member_delete_task', models.BooleanField(default=False)),
                ('member_assign_task', models.BooleanField(default=False)),
                ('member_view_all_tasks', models.BooleanField(default=True)),
                ('member_view_unassigned_tasks', models.BooleanField(default=False)),
                ('member_create_label', models.BooleanField(default=False)),
                ('member_delete_label', models.BooleanField(default=False)),
                ('member_manage_timer', models.BooleanField(default=True)),
                ('member_invite_members', models.BooleanField(default=False)),
                ('member_remove_members', models.BooleanField(default=False)),
                ('member_change_member_roles', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='orgs.organization')),
            ],
            options={
                'verbose_name': 'Organization Permissions',
                'verbose_name_plural': 'Organization Permissions',
            },
        ),
    ]
