# Generated by Django 6.0.1 on 2026-01-27 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, help_text='URL to profile picture', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about the user', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, help_text='Department or team', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, help_text="User's job title", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, help_text='Location/timezone', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_email',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_push',
            field=models.BooleanField(default=True, help_text='Receive push notifications'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website_url',
            field=models.URLField(blank=True, help_text='Personal website URL', null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('task_comment', 'Task Comment'), ('project_invite', 'Project Invitation'), ('org_invite', 'Organization Invitation'), ('mention', 'Mentioned'), ('deadline', 'Deadline Reminder')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL to navigate to when clicked', max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_task_id', models.IntegerField(blank=True, null=True)),
                ('related_project_id', models.IntegerField(blank=True, null=True)),
                ('actor_id', models.IntegerField(blank=True, help_text='User who triggered the notification', null=True)),
                ('actor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='accounts_no_user_id_b29cd4_idx')],
            },
        ),
    ]
