# Generated by Django 5.1.14 on 2026-01-28 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_profile_and_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_data',
            field=models.JSONField(blank=True, default=dict, help_text='Data needed to process action (e.g., invitation_id)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('none', 'No Action Required')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='actor_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_org_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Unique username for mentions and invitations (3-30 chars, letters, numbers, underscores)', max_length=30, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('task_comment', 'Task Comment'), ('project_invite', 'Project Invitation'), ('org_invite', 'Organization Invitation'), ('mention', 'Mentioned'), ('deadline', 'Deadline Reminder'), ('invitation_accepted', 'Invitation Accepted'), ('invitation_declined', 'Invitation Declined'), ('member_left', 'Member Left'), ('account_deleted', 'Account Deleted')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'type', '-created_at'], name='accounts_no_user_id_5a4786_idx'),
        ),
    ]
