# Generated by Django 5.1.14 on 2026-01-28

from django.db import migrations
import re


def generate_username(email, existing_usernames):
    """Generate a unique username from email."""
    # Get the part before @
    base = email.split('@')[0].lower()
    # Remove non-alphanumeric characters except underscore
    base = re.sub(r'[^a-z0-9_]', '', base)
    # Ensure it's at least 3 characters
    if len(base) < 3:
        base = base + 'user'
    
    # Make unique
    username = base
    counter = 1
    while username in existing_usernames:
        username = f"{base}{counter}"
        counter += 1
    
    return username


def populate_usernames(apps, schema_editor):
    """Populate usernames for existing users."""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    existing_usernames = set()
    
    for user in CustomUser.objects.all():
        if not user.username:
            username = generate_username(user.email, existing_usernames)
            user.username = username
            user.save()
            existing_usernames.add(username)
        else:
            existing_usernames.add(user.username)


def reverse_populate_usernames(apps, schema_editor):
    """Reverse: set usernames to empty."""
    pass  # Don't reverse, keep usernames


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_account_fields_step1'),
    ]

    operations = [
        migrations.RunPython(populate_usernames, reverse_populate_usernames),
    ]
