# Generated by Django 5.1.14 on 2026-01-28 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_populate_usernames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Unique username for mentions and invitations (3-30 chars, letters, numbers, underscores)', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
